#! /bin/bash
. gms_init_env.sh -bw$1 $2
build=$1$2
echo $build
export PERL5LIB=${_BASE}/util
cfgfile=perf_gms${DATA_MODEL}.cfg
perl ${_BASE}/util/autotest_perf1.pl cfg=${_BASE}/cfg/${cfgfile} ${build} ${3} ${4}
